// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("backend.Data.Council", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Councils");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Name = "Star Council #1000"
                        });
                });

            modelBuilder.Entity("backend.Data.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CouncilId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CouncilId = 1000,
                            DateOfBirth = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "John",
                            IsPaid = true,
                            LastName = "Doe",
                            MemberNumber = "1234567",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            CouncilId = 1000,
                            DateOfBirth = new DateTime(1985, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Jane",
                            IsPaid = false,
                            LastName = "Smith",
                            MemberNumber = "2345678",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CouncilId = 1000,
                            DateOfBirth = new DateTime(1990, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Bob",
                            IsPaid = true,
                            LastName = "Johnson",
                            MemberNumber = "3456789",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            CouncilId = 1000,
                            DateOfBirth = new DateTime(1975, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            FirstName = "Alice",
                            IsPaid = false,
                            LastName = "Williams",
                            MemberNumber = "4567890",
                            Status = "Associate"
                        });
                });

            modelBuilder.Entity("backend.Data.ProgramActivity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActivityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CouncilId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MoneyDonated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MoneyRaised")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubmitterMemberNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupremeConfirmationNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("VolunteerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VolunteerHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProgramActivities");

                    b.HasData(
                        new
                        {
                            Id = "act-seed-1",
                            ActivityName = "Vocations Support RSVVP",
                            Category = 1,
                            CouncilId = 1000,
                            Description = "Supported vocations via RSVP project.",
                            EventDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            MoneyDonated = 500.00m,
                            MoneyRaised = 0.00m,
                            Status = 3,
                            SubmitterMemberNumber = "1234567",
                            SupremeConfirmationNumber = "SUP-F000001",
                            VolunteerCount = 15,
                            VolunteerHours = 45
                        },
                        new
                        {
                            Id = "act-seed-2",
                            ActivityName = "Family Week Picnic",
                            Category = 2,
                            CouncilId = 1000,
                            Description = "Held our annual family picnic.",
                            EventDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MoneyDonated = 150.00m,
                            MoneyRaised = 250.00m,
                            Status = 3,
                            SubmitterMemberNumber = "1234567",
                            SupremeConfirmationNumber = "SUP-FAM0001",
                            VolunteerCount = 20,
                            VolunteerHours = 60
                        },
                        new
                        {
                            Id = "act-seed-3",
                            ActivityName = "Parish Food Drive",
                            Category = 3,
                            CouncilId = 1000,
                            Description = "Parish food drive collecting non-perishables.",
                            EventDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            MoneyDonated = 100.00m,
                            MoneyRaised = 1200.00m,
                            Status = 3,
                            SubmitterMemberNumber = "2345678",
                            SupremeConfirmationNumber = "SUP-COM0001",
                            VolunteerCount = 12,
                            VolunteerHours = 36
                        },
                        new
                        {
                            Id = "act-seed-4",
                            ActivityName = "March for Life Transportation Support",
                            Category = 4,
                            CouncilId = 1000,
                            Description = "Sponsored bus travel to the March for Life.",
                            EventDate = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            MoneyDonated = 300.00m,
                            MoneyRaised = 0.00m,
                            Status = 3,
                            SubmitterMemberNumber = "3456789",
                            SupremeConfirmationNumber = "SUP-L000001",
                            VolunteerCount = 8,
                            VolunteerHours = 16
                        });
                });

            modelBuilder.Entity("backend.Data.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("CheckNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("CouncilId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LinkedMemberId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = "tx-seed-1",
                            Amount = 1200.00m,
                            CouncilId = 1000,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Proceeds from Parish Food Drive",
                            Type = "INCOME"
                        },
                        new
                        {
                            Id = "tx-seed-2",
                            Amount = 300.00m,
                            CouncilId = 1000,
                            CreatedAt = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bus sponsorship for March for Life",
                            Type = "EXPENSE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
